export default interface GitHubUser {
  login: "ubiquity";
  id: 76412717;
  node_id: "MDEyOk9yZ2FuaXphdGlvbjc2NDEyNzE3";
  avatar_url: "https://avatars.githubusercontent.com/u/76412717?v=4";
  gravatar_id: "";
  url: "https://api.github.com/users/ubiquity";
  html_url: "https://github.com/ubiquity";
  followers_url: "https://api.github.com/users/ubiquity/followers";
  following_url: "https://api.github.com/users/ubiquity/following{/other_user}";
  gists_url: "https://api.github.com/users/ubiquity/gists{/gist_id}";
  starred_url: "https://api.github.com/users/ubiquity/starred{/owner}{/repo}";
  subscriptions_url: "https://api.github.com/users/ubiquity/subscriptions";
  organizations_url: "https://api.github.com/users/ubiquity/orgs";
  repos_url: "https://api.github.com/users/ubiquity/repos";
  events_url: "https://api.github.com/users/ubiquity/events{/privacy}";
  received_events_url: "https://api.github.com/users/ubiquity/received_events";
  type: "Organization" | "User";
  site_admin: boolean;
  name: "Ubiquity DAO";
  company: null;
  blog: "https://ubq.fi";
  location: "mainnet";
  email: null;
  hireable: null;
  bio: "On a mission to create the world's first scalable, sovereign, and secure digital dollar for crypto gaming.";
  twitter_username: "UbiquityDAO";
  public_repos: 24;
  public_gists: 0;
  followers: 11;
  following: 0;
  created_at: "2020-12-21T00:21:13Z";
  updated_at: "2022-09-23T10:32:09Z";
}
